"use client";
import Link from "next/link";
import { useEffect,useState } from "react";
import { api, Application, Campaign, campaignStatusLabels, dateText, Goal, localizeCategory, normalizeCompanyName, userId } from "../lib";

export default function Radar(){
 const [items,setItems]=useState<Campaign[]>([]);const [applications,setApplications]=useState<Application[]>([]);const [goal,setGoal]=useState<Goal|null>(null);const [tab,setTab]=useState<"mine"|"recommended">("mine");const [loading,setLoading]=useState(true);
 useEffect(()=>{Promise.all([api<{items:Campaign[]}>("/campaigns?include_closed=false&limit=100"),api<Goal>(`/goals?user_id=${userId()}`),api<{items:Application[]}>(`/applications?user_id=${userId()}&limit=100`)]).then(([c,g,a])=>{const unique=new Map<string,Campaign>();for(const item of c.items){if(!isEligible(item,g))continue;const company=normalizeCompanyName(item.company_name);const name=normalizeCampaignName(item.name);const key=wechatArticleKey(item.source_url)??[company.toLowerCase(),name.toLowerCase(),item.deadline_at?.slice(0,10)??""].join("|");if(!unique.has(key))unique.set(key,{...item,company_name:company,name,target_graduation_year:normalizeGraduationYear(item.target_graduation_year)})}setItems([...unique.values()]);setApplications(a.items);setGoal(g)}).finally(()=>setLoading(false))},[]);
 const names=new Set(goal?.target_companies.map(c=>normalizeCompanyName(c.company_name))??[]);const shown=items.filter(c=>tab==="mine"?names.has(normalizeCompanyName(c.company_name)):!names.has(normalizeCompanyName(c.company_name)));const joined=new Set(applications.map(a=>a.campaign_id).filter(Boolean));
 return <div className="page"><PageHead eyebrow="机会发现与官方核验" title="秋招雷达" text="根据求职目标筛选招聘项目，并通过官方公众号确认信息来源。"/><div className="tabs"><button className={tab==="mine"?"active":""} onClick={()=>setTab("mine")}>我的目标 <span>{items.filter(c=>names.has(c.company_name)).length}</span></button><button className={tab==="recommended"?"active":""} onClick={()=>setTab("recommended")}>Agent 推荐 <span>{items.filter(c=>!names.has(c.company_name)).length}</span></button></div>
 <section className="card-grid">{loading?<p className="empty-line">正在扫描招聘机会…</p>:shown.length===0?<div className="empty wide"><span>⌁</span><h3>{tab==="mine"?`暂无匹配 ${goal?.graduation_year??"当前"} 届的目标公司项目`:`暂未发现新的匹配项目`}</h3><p>雷达只展示届别匹配且来自真实公众号的招聘项目。</p></div>:shown.map(c=>{const isJoined=joined.has(c.id);return <article className="campaign-card" key={c.id}><div className="company-logo">{c.company_name.slice(0,1)}</div><div className="card-top"><span className="status">{c.status ? (campaignStatusLabels[c.status.toLowerCase()] ?? "开放中") : "开放中"}</span><small>{c.source_name??"微信公众号"}</small></div><h2>{c.company_name}</h2><h3>{c.name}</h3><dl><div><dt>面向届别</dt><dd>{c.target_graduation_year}</dd></div><div><dt>可投方向</dt><dd>{c.position_categories?.length?c.position_categories.map(localizeCategory).join("、"):"暂无信息"}</dd></div><div><dt>招聘城市</dt><dd>{c.cities?.length?c.cities.join("、"):"以官网为准"}</dd></div><div><dt>截止时间</dt><dd>{c.deadline_at?dateText(c.deadline_at):"暂无信息"}</dd></div></dl><div className="card-actions radar-actions"><Link className={isJoined?"secondary joined":"primary"} href={isJoined?"/applications":`/radar/apply/${c.id}`}>{isJoined?"已加入 · 查看投递":"加入我的投递"}</Link><a className="secondary" href={c.application_url??c.source_url!} target="_blank" rel="noreferrer">{c.application_url?"前往投递官网 ↗":"查看公众号原文 ↗"}</a></div></article>})}</section></div>}
function PageHead({eyebrow,title,text}:{eyebrow:string;title:string;text:string}){return <header className="page-head"><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p>{text}</p></header>}
function isEligible(item:Campaign,goal:Goal):boolean{const realWechatSource=Boolean(item.source_url&&item.source_url.includes("mp.weixin.qq.com/s")&&!item.source_url.includes("/mock-"));const notExpired=!item.deadline_at||new Date(item.deadline_at).getTime()>Date.now();const title=normalizeCampaignName(item.name);const recruitmentProject=/校园招聘|校招|秋招|早鸟通道|青云计划|北斗计划|顶尖技术人才计划/.test(title);const excluded=/校园大使|社招|大赛|论文|FAQ/i.test(title);return normalizeGraduationYear(item.target_graduation_year)===goal.graduation_year&&realWechatSource&&notExpired&&recruitmentProject&&!excluded}
function normalizeCampaignName(value:string):string{return value.replace(/\.html?$/i,"").replaceAll("_"," ").replace(/\s+/g," ").trim().replaceAll("Tencent","腾讯").replaceAll("Fall Official Batch","秋招正式批").replaceAll("Campus Recruitment","校园招聘")}
function normalizeGraduationYear(value:string|null):string|null{const match=value?.match(/20\d{2}/);if(match)return match[0];const short=value?.match(/(?:^|\D)(2[5-9])(?:\D|$)/);return short?`20${short[1]}`:value}
function wechatArticleKey(value:string|null):string|null{if(!value)return null;try{const url=new URL(value);const parts=["__biz","mid","idx","sn"].map(key=>url.searchParams.get(key));return parts.every(Boolean)?parts.join("|"):null}catch{return null}}
