"use client";
import Link from "next/link";
import { useEffect,useState } from "react";
import { api,dateText,Schedule,scheduleLabels,scheduleStatusLabels,USER_ID } from "../lib";
export default function SchedulePage(){const [items,setItems]=useState<Schedule[]>([]);const [view,setView]=useState("list");const [show,setShow]=useState(false);const [draft,setDraft]=useState({title:"",schedule_type:"custom",starts_at:"",deadline_at:"",source:"manual"});
 const load=()=>api<{items:Schedule[]}>(`/schedules?user_id=${USER_ID}`).then(x=>setItems(x.items));useEffect(()=>{void load()},[]);
 async function add(e:React.FormEvent){e.preventDefault();await api(`/schedules?user_id=${USER_ID}`,{method:"POST",body:JSON.stringify({...draft,starts_at:draft.starts_at||null,deadline_at:draft.deadline_at||null,status:"pending"})});setShow(false);setDraft({title:"",schedule_type:"custom",starts_at:"",deadline_at:"",source:"manual"});await load()}
 async function complete(id:string){await api(`/schedules/${id}?user_id=${USER_ID}`,{method:"PATCH",body:JSON.stringify({status:"completed"})});await load()}
 const sorted=[...items].sort((a,b)=>(a.starts_at??a.deadline_at??"9999").localeCompare(b.starts_at??b.deadline_at??"9999"));
 return <div className="page"><header className="page-head action-head"><div><p className="eyebrow">关键时间管理</p><h1>日程与提醒</h1><p>统一整理测评、笔试与面试安排，并按个人偏好发送提醒。</p></div><button className="primary" onClick={()=>setShow(true)}>＋ 新建日程</button></header><div className="tabs compact"><button className={view==="list"?"active":""} onClick={()=>setView("list")}>最近日程</button><button className={view==="calendar"?"active":""} onClick={()=>setView("calendar")}>月历</button></div>
 {view==="calendar"?<Calendar items={items}/>:<section className="schedule-list">{sorted.length===0?<div className="empty wide"><span>◷</span><h3>近期没有重要日程</h3><p>授权邮箱后，测评、笔试和面试会自动同步到这里。</p></div>:sorted.map(x=>{const time=x.starts_at??x.deadline_at;return <article key={x.id} className={`schedule-${x.status}`}><div className="date-tile"><strong>{time?new Date(time).getDate():"?"}</strong><span>{time?new Date(time).toLocaleString("zh-CN",{month:"short"}):"待定"}</span></div><div><div className="schedule-tags"><span className="status">{scheduleLabels[x.schedule_type]??"其他日程"}</span><span className={`schedule-state state-${x.status}`}>{scheduleStatusLabels[x.status]??x.status}</span></div><h2>{x.title}</h2><p>{dateText(time)} · {x.source==="manual"?"手动创建":"来自邮箱"}</p>{x.change_log.length>1&&<small className="changed-note">时间有过更新，已保留变更记录</small>}</div><div className="reminder"><span>提醒</span><strong>{reminderSummary(x.reminder_minutes)}</strong></div><div className="schedule-actions">{x.status==="pending"&&<button onClick={()=>complete(x.id)}>标记完成</button>}<Link className="arrow" aria-label={`查看日程 ${x.title}`} href={`/schedule/${x.id}`}>→</Link></div></article>})}</section>}
 {show&&<div className="modal-backdrop" onClick={()=>setShow(false)}><form className="modal" onClick={e=>e.stopPropagation()} onSubmit={add}><h2>新建日程</h2><label>日程标题<input required value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/></label><label>类型<select value={draft.schedule_type} onChange={e=>setDraft({...draft,schedule_type:e.target.value})}>{Object.entries(scheduleLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>开始时间<input type="datetime-local" value={draft.starts_at} onChange={e=>setDraft({...draft,starts_at:e.target.value})}/></label><div><button type="button" className="secondary" onClick={()=>setShow(false)}>取消</button><button className="primary">保存日程</button></div></form></div>}</div>}
function reminderSummary(values:number[]){if(!values.length)return "已关闭";return values.map(v=>v===0?"当天":v%1440===0?`提前 ${v/1440} 天`:`提前 ${v/60} 小时`).join("、")}
function Calendar({items}:{items:Schedule[]}){const now=new Date();const days=new Date(now.getFullYear(),now.getMonth()+1,0).getDate();const first=new Date(now.getFullYear(),now.getMonth(),1).getDay();const marked=new Set(items.filter(x=>x.status==="pending").map(x=>new Date(x.starts_at??x.deadline_at??0)).filter(d=>d.getFullYear()===now.getFullYear()&&d.getMonth()===now.getMonth()).map(d=>d.getDate()));return <section className="calendar"><header><button aria-label="上个月">‹</button><h2>{now.getFullYear()} 年 {now.getMonth()+1} 月</h2><button aria-label="下个月">›</button></header><div className="week">{"日一二三四五六".split("").map(x=><span key={x}>{x}</span>)}</div><div className="days">{Array.from({length:first}).map((_,i)=><span key={`b${i}`}/>) }{Array.from({length:days},(_,i)=>i+1).map(d=><button key={d} className={`${d===now.getDate()?"today":""} ${marked.has(d)?"marked":""}`}>{d}</button>)}</div></section>}
