"use client";
import Link from "next/link";
import { useParams,useRouter } from "next/navigation";
import { FormEvent,useEffect,useState } from "react";
import { api,Application,Campaign,dateText,Schedule,scheduleLabels,scheduleStatusLabels,userId } from "../../lib";

const reminderOptions=[{value:4320,label:"提前 3 天"},{value:1440,label:"提前 1 天"},{value:120,label:"提前 2 小时"},{value:60,label:"提前 1 小时"},{value:0,label:"当天"}];

export default function ScheduleDetail(){const {scheduleId}=useParams<{scheduleId:string}>();const router=useRouter();const [item,setItem]=useState<Schedule|null>(null);const [application,setApplication]=useState<Application|null>(null);const [campaign,setCampaign]=useState<Campaign|null>(null);const [editing,setEditing]=useState(false);const [confirmCancel,setConfirmCancel]=useState(false);const [missing,setMissing]=useState(false);const [message,setMessage]=useState("");const [draft,setDraft]=useState({title:"",status:"pending",time:"",reminder_minutes:[] as number[]});
 useEffect(()=>{load()},[scheduleId]);function load(){api<Schedule>(`/schedules/${scheduleId}?user_id=${userId()}`).then(async value=>{setItem(value);setDraft({title:value.title,status:value.status,time:toLocalInput(value.starts_at??value.deadline_at),reminder_minutes:value.reminder_minutes});const [relatedApplication,relatedCampaign]=await Promise.all([value.application_id?api<Application>(`/applications/${value.application_id}?user_id=${userId()}`).catch(()=>null):Promise.resolve(null),value.campaign_id?api<Campaign>(`/campaigns/${value.campaign_id}`).catch(()=>null):Promise.resolve(null)]);setApplication(relatedApplication);setCampaign(relatedCampaign)}).catch(()=>setMissing(true))}
 async function save(e:FormEvent){e.preventDefault();if(!item)return;const timeField=["application_deadline","assessment_deadline","offer_response_deadline"].includes(item.schedule_type)?"deadline_at":"starts_at";const updated=await api<Schedule>(`/schedules/${scheduleId}?user_id=${userId()}`,{method:"PATCH",body:JSON.stringify({title:draft.title,status:draft.status,[timeField]:draft.time||null,reminder_minutes:draft.reminder_minutes})});setItem(updated);setEditing(false);setMessage("日程与提醒设置已更新");setTimeout(()=>setMessage(""),2500)}
 async function cancel(){await api(`/schedules/${scheduleId}?user_id=${userId()}`,{method:"DELETE"});router.push("/schedule")}
 function toggleReminder(value:number){setDraft({...draft,reminder_minutes:draft.reminder_minutes.includes(value)?draft.reminder_minutes.filter(x=>x!==value):[...draft.reminder_minutes,value]})}
 if(missing)return <div className="page"><div className="empty wide"><h3>没有找到这条日程</h3><Link className="text-link" href="/schedule">返回日程与提醒</Link></div></div>;if(!item)return <div className="page"><p className="empty-line">正在读取日程…</p></div>;
 const time=item.starts_at??item.deadline_at;return <div className="page schedule-detail-page"><Link className="back-link" href="/schedule">← 返回日程与提醒</Link>{message&&<p className="notice global">{message}</p>}<header className="detail-hero schedule-hero"><div className="date-tile large-date"><strong>{time?new Date(time).getDate():"?"}</strong><span>{time?new Date(time).toLocaleString("zh-CN",{month:"short"}):"待定"}</span></div><div><p className="eyebrow">{scheduleLabels[item.schedule_type]}</p><h1>{item.title}</h1><p>{dateText(time)}</p></div><div className={`stage-pill state-${item.status}`}><span>日程状态</span><strong>{scheduleStatusLabels[item.status]}</strong></div></header><div className="detail-layout"><main><section className="detail-card"><div className="detail-title"><div><p className="eyebrow">日程信息</p><h2>{application?`${application.company_name} · ${application.position_name}`:campaign?.company_name??"自定义日程"}</h2></div><button className="secondary" onClick={()=>setEditing(true)}>编辑日程</button></div><dl className="detail-facts"><div><dt>招聘项目</dt><dd>{campaign?.name??"未关联"}</dd></div><div><dt>日程类型</dt><dd>{scheduleLabels[item.schedule_type]}</dd></div><div><dt>时间</dt><dd>{dateText(time)}</dd></div><div><dt>来源</dt><dd>{item.source==="manual"?"手动创建":"邮箱自动同步"}</dd></div></dl>{application&&<div className="detail-links"><Link href={`/applications/${application.id}`}>查看对应投递 →</Link></div>}</section><section className="detail-card"><p className="eyebrow">提醒设置</p><h2 className="card-heading">{item.reminder_minutes.length?reminderText(item.reminder_minutes):"提醒已关闭"}</h2><p className="detail-description">改期时保留你的提醒偏好；取消或完成后不再发送后续提醒。</p><button className="secondary" onClick={()=>setEditing(true)}>修改提醒</button></section><section className="detail-card timeline-card"><p className="eyebrow">变更记录</p><h2>历史变化</h2>{item.change_log.length===0?<div className="timeline-empty">这条日程还没有发生变更。</div>:<ol className="timeline">{[...item.change_log].reverse().map((entry,index)=><li key={`${entry.changed_at}-${index}`} className={index===0?"latest":""}><i/><div><strong>{changeText(entry.changes??{})}</strong><span>{entry.changed_at?dateText(entry.changed_at):"时间未知"}</span></div></li>)}</ol>}</section></main><aside className="detail-card danger-card"><p className="eyebrow">日程管理</p><h3>取消这条日程</h3><p>取消后会保留历史记录，但不再发送后续提醒。</p><button className="danger-button" disabled={item.status==="canceled"} onClick={()=>setConfirmCancel(true)}>{item.status==="canceled"?"日程已取消":"取消日程"}</button></aside></div>
 {editing&&<div className="modal-backdrop" onClick={()=>setEditing(false)}><form className="modal schedule-edit-modal" onClick={e=>e.stopPropagation()} onSubmit={save}><h2>编辑日程</h2><label>日程标题<input required value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/></label><label>时间<input type="datetime-local" value={draft.time} onChange={e=>setDraft({...draft,time:e.target.value})}/></label><label>状态<select value={draft.status} onChange={e=>setDraft({...draft,status:e.target.value})}>{Object.entries(scheduleStatusLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><fieldset><legend>提醒时间</legend><div className="reminder-options">{reminderOptions.map(option=><label key={option.value}><input type="checkbox" checked={draft.reminder_minutes.includes(option.value)} onChange={()=>toggleReminder(option.value)}/><span>{option.label}</span></label>)}</div><small>全部取消勾选即可关闭提醒。</small></fieldset><div><button type="button" className="secondary" onClick={()=>setEditing(false)}>取消</button><button className="primary">保存修改</button></div></form></div>}
 {confirmCancel&&<div className="modal-backdrop" onClick={()=>setConfirmCancel(false)}><div className="modal confirm-modal" onClick={e=>e.stopPropagation()}><h2>确认取消日程？</h2><p>“{item.title}”会标记为已取消并停止提醒，历史记录仍然保留。</p><div><button className="secondary" onClick={()=>setConfirmCancel(false)}>返回</button><button className="danger-button solid" onClick={cancel}>确认取消</button></div></div></div>}</div>}
function toLocalInput(value:string|null){if(!value)return "";const date=new Date(value);const local=new Date(date.getTime()-date.getTimezoneOffset()*60000);return local.toISOString().slice(0,16)}
function reminderText(values:number[]){return [...values].sort((a,b)=>b-a).map(v=>v===0?"当天提醒":v%1440===0?`提前 ${v/1440} 天`:`提前 ${v/60} 小时`).join("、")}
function changeText(changes:Record<string,unknown>){if("created_from_event_id" in changes)return "从招聘邮件创建日程";if("updated_from_event_id" in changes)return "招聘时间已自动更新";if("canceled_from_event_id" in changes)return "招聘方取消了日程";if("reminder_minutes" in changes)return "提醒设置已修改";if("status" in changes)return `状态更新为${scheduleStatusLabels[String(changes.status)]??changes.status}`;return "日程信息已修改"}
