"use client";
import Link from "next/link";
import { useParams,useRouter } from "next/navigation";
import { FormEvent,useEffect,useState } from "react";
import { api,Application,Campaign,eventLabels,RecruitmentEvent,stageLabels,userId } from "../../lib";

const stages=["submitted","assessment","written_test","interview_1","interview_2","interview_3","cross_interview","hr_interview","offer","failed"];

export default function ApplicationDetail(){
 const {applicationId}=useParams<{applicationId:string}>();const router=useRouter();const [item,setItem]=useState<Application|null>(null);const [campaign,setCampaign]=useState<Campaign|null>(null);const [events,setEvents]=useState<RecruitmentEvent[]>([]);const [editing,setEditing]=useState(false);const [confirmDelete,setConfirmDelete]=useState(false);const [draft,setDraft]=useState({position_name:"",stage:"submitted"});const [message,setMessage]=useState("");const [missing,setMissing]=useState(false);
 useEffect(()=>{api<Application>(`/applications/${applicationId}?user_id=${userId()}`).then(async value=>{setItem(value);setDraft({position_name:value.position_name,stage:value.stage});const requests:[Promise<{items:RecruitmentEvent[]}>,Promise<Campaign|null>]=[api<{items:RecruitmentEvent[]}>(`/events?user_id=${userId()}&application_id=${applicationId}&limit=100`),value.campaign_id?api<Campaign>(`/campaigns/${value.campaign_id}`).catch(()=>null):Promise.resolve(null)];const [history,relatedCampaign]=await Promise.all(requests);setEvents(history.items);setCampaign(relatedCampaign)}).catch(()=>setMissing(true))},[applicationId]);
 async function save(e:FormEvent){e.preventDefault();const updated=await api<Application>(`/applications/${applicationId}?user_id=${userId()}`,{method:"PATCH",body:JSON.stringify(draft)});setItem(updated);setEditing(false);setMessage("投递信息已更新");setTimeout(()=>setMessage(""),2500)}
 async function remove(){await api(`/applications/${applicationId}?user_id=${userId()}`,{method:"DELETE"});router.push("/applications")}
 if(missing)return <div className="page"><div className="empty wide"><h3>没有找到这条投递记录</h3><Link className="text-link" href="/applications">返回我的投递</Link></div></div>;
 if(!item)return <div className="page"><p className="empty-line">正在读取投递进度…</p></div>;
 return <div className="page application-detail-page"><Link className="back-link" href="/applications">← 返回我的投递</Link>{message&&<p className="notice global">{message}</p>}<header className="detail-hero"><div className="company-logo large-logo">{item.company_name.slice(0,1)}</div><div><p className="eyebrow">{sourceText(item.source)}</p><h1>{item.company_name}</h1><p>{campaign?.name??"手动创建的投递"}</p></div><div className={`stage-pill stage-${item.stage}`}><span>当前阶段</span><strong>{stageLabels[item.stage]}</strong></div></header><div className="detail-layout"><main><section className="detail-card"><div className="detail-title"><div><p className="eyebrow">投递信息</p><h2>{item.position_name}</h2></div><button className="secondary" onClick={()=>setEditing(true)}>编辑</button></div><dl className="detail-facts"><div><dt>招聘项目</dt><dd>{campaign?.name??"未关联"}</dd></div><div><dt>当前阶段</dt><dd>{stageLabels[item.stage]}</dd></div><div><dt>记录来源</dt><dd>{sourceText(item.source)}</dd></div><div><dt>最近更新</dt><dd>{formatTime(item.last_changed_at)}</dd></div></dl>{campaign&&<div className="detail-links"><Link href={`/radar/apply/${campaign.id}`}>查看招聘项目</Link><a href={campaign.application_url??campaign.source_url!} target="_blank" rel="noreferrer">查看官方来源 ↗</a></div>}</section><section className="detail-card timeline-card"><p className="eyebrow">流程时间线</p><h2>招聘进展</h2>{events.length===0?<div className="timeline-empty">新的招聘进展将在邮箱同步后显示。</div>:<ol className="timeline">{events.map((event,index)=><li key={event.id} className={index===0?"latest":""}><i/><div><strong>{eventLabels[event.event_type]??event.event_type}</strong><span>{formatTime(event.occurred_at)} · {sourceText(event.source)}</span></div></li>)}</ol>}</section></main><aside className="detail-card danger-card"><p className="eyebrow">记录管理</p><h3>删除这条投递</h3><p>删除后将不再出现在“我的投递”中，已有流程事件仍会按系统规则保留。</p><button className="danger-button" onClick={()=>setConfirmDelete(true)}>删除投递记录</button></aside></div>
 {editing&&<div className="modal-backdrop" onClick={()=>setEditing(false)}><form className="modal" onClick={e=>e.stopPropagation()} onSubmit={save}><h2>编辑投递</h2><label>投递岗位<input required value={draft.position_name} onChange={e=>setDraft({...draft,position_name:e.target.value})}/></label><label>当前阶段<select value={draft.stage} onChange={e=>setDraft({...draft,stage:e.target.value})}>{stages.map(stage=><option key={stage} value={stage}>{stageLabels[stage]}</option>)}</select></label><div><button type="button" className="secondary" onClick={()=>setEditing(false)}>取消</button><button className="primary">保存修改</button></div></form></div>}
 {confirmDelete&&<div className="modal-backdrop" onClick={()=>setConfirmDelete(false)}><div className="modal confirm-modal" onClick={e=>e.stopPropagation()}><h2>确认删除？</h2><p>将删除“{item.company_name} · {item.position_name}”这条投递记录。此操作无法在页面中撤销。</p><div><button className="secondary" onClick={()=>setConfirmDelete(false)}>取消</button><button className="danger-button solid" onClick={remove}>确认删除</button></div></div></div>}</div>
}
function sourceText(source:string){return source==="manual"?"手动记录":source==="radar"?"秋招雷达":source.includes("email")?"邮箱同步":source==="official_wechat"?"微信公众号":source}
function formatTime(value:string){return new Intl.DateTimeFormat("zh-CN",{year:"numeric",month:"short",day:"numeric",hour:"2-digit",minute:"2-digit"}).format(new Date(value))}
