"use client";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { api, Application, Campaign, EmailSyncResult, stageLabels, USER_ID } from "../lib";

export default function Applications() {
 const [items,setItems]=useState<Application[]>([]); const [campaigns,setCampaigns]=useState<Campaign[]>([]); const [q,setQ]=useState(""); const [filter,setFilter]=useState("all"); const [show,setShow]=useState(false); const [syncing,setSyncing]=useState(false); const [syncMessage,setSyncMessage]=useState(""); const [lastSyncedAt,setLastSyncedAt]=useState(""); const [draft,setDraft]=useState({company_name:"",position_name:""});
 const load=()=>Promise.all([api<{items:Application[]}>(`/applications?user_id=${USER_ID}`),api<{items:Campaign[]}>("/campaigns?include_closed=true&limit=100")]).then(([a,c])=>{setItems(a.items);setCampaigns(c.items)});
 useEffect(()=>{void load();setLastSyncedAt(localStorage.getItem("campus-agent:last-email-sync")??"")},[]);
 const campaignNames=new Map(campaigns.map(c=>[c.id,c.name]));
 const shown=useMemo(()=>items.filter(x=>(x.company_name+x.position_name).toLowerCase().includes(q.toLowerCase())&&(filter==="all"||(filter==="active"&&!['offer','failed'].includes(x.stage))||x.stage===filter)).sort((a,b)=>b.last_changed_at.localeCompare(a.last_changed_at)),[items,q,filter]);
 async function add(e:React.FormEvent){e.preventDefault();await api(`/applications?user_id=${USER_ID}`,{method:"POST",body:JSON.stringify({...draft,stage:"submitted",source:"manual"})});setShow(false);setDraft({company_name:"",position_name:""});await load()}
 async function syncEmail(){setSyncing(true);setSyncMessage("");try{const result=await api<EmailSyncResult>(`/email-imports/qq/sync?user_id=${USER_ID}&replan=true`,{method:"POST"});if(!result.ok)throw new Error(result.reason??"sync-failed");const now=new Date().toISOString();localStorage.setItem("campus-agent:last-email-sync",now);setLastSyncedAt(now);await load();setSyncMessage(result.imported_count?`更新完成：扫描 ${result.scanned_count} 封邮件，识别 ${result.imported_count} 条新进展。`:`已检查 ${result.scanned_count} 封邮件，暂无新的招聘进展。`)}catch{setSyncMessage("更新失败，请到“我的”检查邮箱授权配置。")}finally{setSyncing(false)}}
 return <div className="page"><header className="page-head action-head"><div><p className="eyebrow">投递进展管理</p><h1>我的投递</h1><p>集中管理岗位记录与招聘阶段，最新变化优先呈现。</p>{lastSyncedAt&&<small className="sync-time">邮箱最近更新：{new Intl.DateTimeFormat("zh-CN",{month:"numeric",day:"numeric",hour:"2-digit",minute:"2-digit"}).format(new Date(lastSyncedAt))}</small>}</div><div className="head-actions"><button className="secondary" onClick={syncEmail} disabled={syncing}>{syncing?"正在读取邮箱…":"↻ 一键更新邮箱"}</button><button className="primary" onClick={()=>setShow(true)}>＋ 新建投递</button></div></header>{syncMessage&&<p className="notice sync-notice">{syncMessage}</p>}<div className="toolbar"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="搜索公司或岗位"/><div className="filter-row">{[["all","全部"],["active","进行中"],["offer","Offer"],["failed","已挂"]].map(([v,l])=><button className={filter===v?"active":""} key={v} onClick={()=>setFilter(v)}>{l}</button>)}</div></div>
 <section className="application-list">{shown.length===0?<div className="empty wide"><span>▤</span><h3>还没有匹配的投递记录</h3><p>从秋招雷达加入、一键更新邮箱，或手动添加第一条投递。</p></div>:shown.map(x=><article key={x.id}><div className="company-logo">{x.company_name.slice(0,1)}</div><div className="application-main"><small>{x.source==="manual"?"手动记录":x.source==="radar"?"秋招雷达":"邮箱同步"}</small><h2>{x.company_name}</h2>{x.campaign_id&&<span className="campaign-name">{campaignNames.get(x.campaign_id)??"招聘项目"}</span>}<p>{x.position_name}</p></div><div className={`stage stage-${x.stage}`}><span>当前阶段</span><strong>{stageLabels[x.stage]??"状态待确认"}</strong></div><time>更新于 {new Intl.DateTimeFormat("zh-CN",{month:"numeric",day:"numeric",hour:"2-digit",minute:"2-digit"}).format(new Date(x.last_changed_at))}</time><Link className="arrow" aria-label={`查看 ${x.company_name} ${x.position_name}`} href={`/applications/${x.id}`}>→</Link></article>)}</section>
 {show&&<div className="modal-backdrop" onClick={()=>setShow(false)}><form className="modal" onClick={e=>e.stopPropagation()} onSubmit={add}><h2>新建投递</h2><label>公司名称<input required value={draft.company_name} onChange={e=>setDraft({...draft,company_name:e.target.value})}/></label><label>投递岗位<input required value={draft.position_name} onChange={e=>setDraft({...draft,position_name:e.target.value})}/></label><div><button type="button" className="secondary" onClick={()=>setShow(false)}>取消</button><button className="primary">保存投递</button></div></form></div>}</div>
}
