"use client";
import Link from "next/link";
import { useParams,useRouter } from "next/navigation";
import { FormEvent,useEffect,useState } from "react";
import { api, Application, Campaign, localizeCategory, USER_ID } from "../../../lib";

export default function AddCampaignApplication(){
 const {campaignId}=useParams<{campaignId:string}>();const router=useRouter();const [campaign,setCampaign]=useState<Campaign|null>(null);const [position,setPosition]=useState("");const [saving,setSaving]=useState(false);const [error,setError]=useState("");
 useEffect(()=>{api<Campaign>(`/campaigns/${campaignId}`).then(c=>{setCampaign(c);if(c.position_categories?.length===1)setPosition(localizeCategory(c.position_categories[0]))}).catch(()=>setError("没有找到这个招聘项目"))},[campaignId]);
 async function submit(e:FormEvent){e.preventDefault();if(!campaign)return;setSaving(true);setError("");try{await api<Application>(`/applications?user_id=${USER_ID}`,{method:"POST",body:JSON.stringify({campaign_id:campaign.id,company_name:campaign.company_name,position_name:position,stage:"submitted",source:"radar"})});router.push("/applications?added=1")}catch{setError("保存失败，请稍后重试");setSaving(false)}}
 if(error&&!campaign)return <div className="page"><div className="empty wide"><h3>{error}</h3><Link className="text-link" href="/radar">返回秋招雷达</Link></div></div>;
 if(!campaign)return <div className="page"><p className="empty-line">正在读取招聘项目…</p></div>;
 return <div className="page apply-page"><Link className="back-link" href="/radar">← 返回秋招雷达</Link><header className="page-head"><p className="eyebrow">加入我的投递</p><h1>确认投递信息</h1><p>这里记录你的实际投递岗位，不会替你自动提交简历。</p></header><div className="apply-layout"><section className="apply-summary"><span className="status">开放中</span><div className="company-logo">{campaign.company_name.slice(0,1)}</div><h2>{campaign.company_name}</h2><h3>{campaign.name}</h3><dl><div><dt>可投方向</dt><dd>{campaign.position_categories?.length?campaign.position_categories.map(localizeCategory).join("、"):"以招聘官网为准"}</dd></div><div><dt>招聘城市</dt><dd>{campaign.cities?.length?campaign.cities.join("、"):"以招聘官网为准"}</dd></div></dl><a href={campaign.application_url??campaign.source_url!} target="_blank" rel="noreferrer">{campaign.application_url?"打开官方投递入口 ↗":"打开公众号原文确认岗位 ↗"}</a></section><form className="apply-form" onSubmit={submit}><h2>你准备投递哪个岗位？</h2><p>一个岗位对应一条投递记录；同一项目的不同岗位可以分别添加。</p>{campaign.position_categories?.length?<div className="suggestions">{campaign.position_categories.map(x=>{const label=localizeCategory(x);return <button type="button" key={x} onClick={()=>setPosition(label)}>{label}</button>})}</div>:null}<label>具体岗位名称<input autoFocus required maxLength={255} placeholder="例如：AI 产品经理" value={position} onChange={e=>setPosition(e.target.value)}/></label>{error&&<p className="form-error">{error}</p>}<div className="form-actions"><Link className="secondary" href="/radar">取消</Link><button className="primary" disabled={saving}>{saving?"保存中…":"确认加入"}</button></div><small>确认后会进入“我的投递”，初始阶段为“已投递”。</small></form></div></div>;
}
