"use client";
import Link from "next/link";
import { useEffect,useState } from "react";
import { api,EmailSyncResult,Goal,Priority,USER_ID } from "../lib";
const empty:Goal={graduation_year:"2027",target_positions:[],target_cities:[],target_industries:[],target_companies:[]};
export default function Me(){const [goal,setGoal]=useState<Goal>(empty);const [editing,setEditing]=useState(false);const [syncing,setSyncing]=useState(false);const [message,setMessage]=useState("");useEffect(()=>{api<Goal>(`/goals?user_id=${USER_ID}`).then(setGoal).catch(()=>{})},[]);
 async function save(){await api(`/goals?user_id=${USER_ID}`,{method:"PATCH",body:JSON.stringify(goal)});setEditing(false);setMessage("求职目标已更新。")}
 async function sync(){setSyncing(true);try{const result=await api<EmailSyncResult>(`/email-imports/qq/sync?user_id=${USER_ID}&replan=true`,{method:"POST"});if(!result.ok)throw new Error(result.reason??"sync-failed");localStorage.setItem("campus-agent:last-email-sync",new Date().toISOString());setMessage(result.imported_count?`邮箱更新完成：识别 ${result.imported_count} 条新进展。`:`已检查 ${result.scanned_count} 封邮件，暂无新的招聘进展。`)}catch{setMessage("更新失败，请检查邮箱授权配置。")}setSyncing(false)}
 return <div className="page"><header className="page-head"><p className="eyebrow">求职偏好与账户</p><h1>我的</h1><p>调整目标方向、提醒方式与数据授权。</p></header>{message&&<p className="notice global">{message}</p>}<section className="settings-section"><div className="settings-title"><div><span>01</span><h2>求职目标设置</h2><p>用于雷达匹配、优先级判断和每日计划。</p></div><button className="secondary" onClick={()=>editing?void save():setEditing(true)}>{editing?"保存修改":"编辑"}</button></div>
 <div className="goal-summary"><Summary label="求职届别" value={`${goal.graduation_year}${goal.graduation_year!=="社招"?" 届":""}`}/><Summary label="目标岗位" value={goal.target_positions.join("、")||"未设置"}/><Summary label="目标城市" value={goal.target_cities.join("、")||"未设置"}/><Summary label="目标行业" value={goal.target_industries.join("、")||"未设置"}/></div>
 <div className="target-list"><h3>目标公司</h3>{goal.target_companies.map(c=><div key={c.company_name}><span className={`priority ${c.priority}`}>{c.priority}</span><strong>{c.company_name}</strong>{editing?<select value={c.priority} onChange={e=>setGoal({...goal,target_companies:goal.target_companies.map(x=>x.company_name===c.company_name?{...x,priority:e.target.value as Priority}:x)})}><option value="dream">Dream · 冲刺</option><option value="target">Target · 重点</option><option value="safe">Safe · 保底</option></select>:<small>{c.priority==="dream"?"冲刺":c.priority==="target"?"重点":"保底"}</small>}</div>)}</div><Link href="/onboarding" className="text-link">重新完整设置 →</Link></section>
 <section className="settings-section"><div className="settings-title"><div><span>02</span><h2>提醒偏好</h2><p>系统按节点类型异步生成默认提醒。</p></div></div><div className="preference-list"><Preference title="截止事项" text="提前 3 天、1 天、当天提醒"/><Preference title="面试" text="提前 1 天、2 小时提醒"/><Preference title="笔试" text="提前 1 天、1 小时提醒"/></div></section>
 <section className="settings-section"><div className="settings-title"><div><span>03</span><h2>权限与隐私</h2><p>邮箱只用于识别招聘进展，不会代你回复邮件。</p></div></div><div className="permission-card"><div className="permission-icon">✉</div><div><h3>招聘邮箱同步</h3><p>同步投递成功、测评、笔试、面试、Offer 和拒信。</p><span className="safe-text">只读取招聘相关邮件 · 数据用于当前账号</span></div><button className="primary" onClick={sync} disabled={syncing}>{syncing?"同步中…":"立即同步"}</button></div><div className="privacy-note"><strong>你的数据边界</strong><p>Campus Agent 不会自动投递、自动回复邮件或替你确认面试。你可以随时停止邮箱同步。</p></div></section></div>}
function Summary({label,value}:{label:string;value:string}){return <div><span>{label}</span><strong>{value}</strong></div>}function Preference({title,text}:{title:string;text:string}){return <div><div><strong>{title}</strong><p>{text}</p></div><label className="switch"><input type="checkbox" defaultChecked/><span/></label></div>}
